format_version: 3
pipelines:
  node-ci:
    group: NODEJS-GOCD
    materials:
      node-pr-listener:
        git: git@github.com:sarangkartikey50/nodejs-github-actions.git
        autoUpdate: false
        shallowClose: true
        branch: main
    stages:
      - install-dependencies:
          clean_workspace: true
          jobs:
            lint-checks:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - "npm i"
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - "npm run lint"