format_version: 3
pipelines:
  node-ci:
    group: NODEJS-GOCD
    materials:
      mygit:
        git: git@github.com:sarangkartikey50/nodejs-github-actions.git
        autoUpdate: false
        shallowClose: false
        branch: main
    stages:
      - install-dependencies:
          clean_workspace: true
          jobs:
            lint-checks:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - "npm i"
  build:
    group: NODEJS-GOCD
    materials:
      mygit:
        git: git@github.com:sarangkartikey50/nodejs-github-actions.git
        autoUpdate: false
        shallowClone: false
        branch: main
    stages:
      - build-and-test:
        clean_workspace: true
        jobs:
          build:
            tasks:
              - exec:
                  command: bash
                  arguments:
                    - "-c"
                    - "npm run build"
        jobs:
          test:
            tasks:
              - exec:
                  command: bash
                  arguments:
                    - "-c"
                    - "npm run test"
              - exec:
                  command: bash
                  arguments:
                    - "-c"
                    - "npm run lint"