format_version: 3
pipelines:
  build-and-test:
    group: NODEJS-GOCD
    materials:
      mygit:
        git: git@github.com:sarangkartikey50/nodejs-github-actions.git
        autoUpdate: false
        shallowClone: false
        branch: main
    stages:
      - install-dependencies:
          clean_workspace: true
          keep_artifacts: true
          approval:
            type: success
          jobs:
            install:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - "npm i"
      - create-build:
          clean_workspace: true
          keep_artifacts: true
          approval:
            type: success
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - "npm run build"
      - run-tests:
          clean_workspace: true
          keep_artifacts: true
          approval:
            type: success
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - "npm run test"
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - "npm run lint"
